version: "3.5"

services:
  postgres:
    image: postgres:15
    container_name: crawler-masterdb-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: masterdb
    ports:
      - 5433:5432
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
  redis:
    image: bitnami/redis:latest
    container_name: crawler-masterdb-redis
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    #ports:
    #  - 6379:6379
    volumes:
      - ../redis_data:/bitnami/redis/data
  api:
    image: u2labs/crawler-masterdb:latest
    build:
      context: .
    container_name: crawler-masterdb-api
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - 9001:8085
    command: "layerg-poi-da api --config config.yaml"
    volumes:
      - ./config.yaml:/go/bin/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: 300m
